# Generated by Django 5.2.7 on 2025-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ASC', 'Adulto Sin Documento'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('MSC', 'Menor de Edad Sin Documento'), ('NUIP', 'Número Único de Identificación Personal'), ('PAS', 'Pasaporte'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('PPT', 'Permiso de Permanencia Temporal')], max_length=10)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=200)),
                ('departameto', models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLANTICO', 'Atlántico'), ('BOGOTA', 'Bogotá D.C.'), ('BOLIVAR', 'Bolívar'), ('BOYACA', 'Boyacá'), ('CALDAS', 'Caldas'), ('CAQUETA', 'Caquetá'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCO', 'Chocó'), ('CORDOBA', 'Córdoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINIA', 'Guainía'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('LA GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARIÑO', 'Nariño'), ('NORTE DE SANTANDER', 'Norte de Santander'), ('PUTUMAYO', 'Putumayo'), ('QUINDIO', 'Quindío'), ('RISARALDA', 'Risaralda'), ('SAN ANDRES Y PROVIDENCIA', 'San Andrés y Providencia'), ('SANTANDER', 'Santander'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE DEL CAUCA', 'Valle del Cauca'), ('VAUPES', 'Vaupés'), ('VICHADA', 'Vichada')], max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('zona_residencia', models.CharField(choices=[('RURAL', 'Rural'), ('URBANA', 'Urbana')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('UNION LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo'), ('DIVORCIADO', 'Divorciado')], max_length=15)),
                ('ocupacion', models.CharField(max_length=100)),
                ('entidad_salud', models.CharField(choices=[('EPS1', 'Entidad Promotora de Salud 1'), ('EPS2', 'Entidad Promotora de Salud 2'), ('EPS3', 'Entidad Promotora de Salud 3'), ('OTRA', 'Otra')], max_length=100)),
                ('tipo_afiliacion', models.CharField(choices=[('CONTRIBUTIVO', 'Contributivo'), ('SUBSIDIADO', 'Subsidiado'), ('VINCULADO', 'Vinculado'), ('NINGUNO', 'Ninguno')], max_length=20)),
                ('regimen', models.CharField(choices=[('Contributivo Cotizante', 'Contributivo Cotizante'), ('Subsidiado', 'Subsidiado')], max_length=200)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=10)),
            ],
        ),
    ]
