# Generated by Django 5.2.7 on 2025-11-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('FONOAUDIOLOGIA', 'Consulta de Fonoaudiología'), ('PSICOLOGIA', 'Consulta de Psicología')], max_length=100)),
                ('fecha_consulta', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
