# Generated by Django 5.2.7 on 2025-11-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_consulta_tipo_consulta_consultapsicologia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
