# Generated by Django 5.2.7 on 2025-11-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_delete_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaNeumologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('presion_arterial', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.CharField(max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
