# Generated by Django 5.2.7 on 2025-11-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_consultaneumologia_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaneumologia',
            name='fecha_consulta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultapsicologia',
            name='fecha_consulta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
