# Generated by Django 6.0.1 on 2026-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PE', 'Permiso Especial de Permanencia')], max_length=3)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('direccion', models.CharField(max_length=300)),
                ('barrio', models.CharField(max_length=100)),
                ('departamento', models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLÁNTICO', 'Atlántico'), ('BOLÍVAR', 'Bolívar'), ('BOYACÁ', 'Boyacá'), ('CALDAS', 'Caldas'), ('CAQUETÁ', 'Caquetá'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCÓ', 'Chocó'), ('CÓRDOBA', 'Córdoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINÍA', 'Guainía'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('LA GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARIÑO', 'Nariño'), ('NORTE DE SANTANDER', 'Norte de Santander'), ('PUTUMAYO', 'Putumayo'), ('QUINDÍO', 'Quindío'), ('RISARALDA', 'Risaralda'), ('SAN ANDRÉS Y PROVIDENCIA', 'San Andrés y Providencia'), ('SANTANDER', 'Santander'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE DEL CAUCA', 'Valle del Cauca'), ('VAUPÉS', 'Vaupés'), ('VICHADA', 'Vichada')], max_length=100)),
                ('ciudad', models.CharField(choices=[('BUCARAMANGA', 'Bucaramanga'), ('MEDELLÍN', 'Medellín'), ('BOGOTÁ', 'Bogotá'), ('CARTAGENA', 'Cartagena'), ('BARRANQUILLA', 'Barranquilla'), ('MEDELLÍN', 'Medellín'), ('BOGOTÁ', 'Bogotá'), ('CARTAGENA', 'Cartagena'), ('BARRANQUILLA', 'Barranquilla')], max_length=100)),
                ('zona', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('UNIÓN LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo'), ('DIVORCIADO', 'Divorciado')], max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('entidad_salud', models.CharField(choices=[('ECOPETROL', 'Ecopetrol'), ('SANITAS', 'Sanitas')], max_length=100)),
                ('estrato', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('perimetro_abdominal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuello', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medico_remitente', models.CharField(choices=[('DR. JUAN PÉREZ', 'Dr. Juan Pérez'), ('DRA. MARÍA GÓMEZ', 'Dra. María Gómez')], max_length=100)),
                ('especialidad', models.CharField(choices=[('MEDICINA GENERAL', 'Medicina General'), ('CARDIOLOGÍA', 'Cardiología'), ('NEUMOLOGÍA', 'Neumología')], max_length=100)),
                ('diagnostico_clinico', models.TextField(choices=[('G47.3', 'Apnea del Sueño'), ('I10', 'Hipertensión Esencial (Primaria)'), ('E66.9', 'Obesidad No Especificada')], max_length=1000)),
                ('programa', models.CharField(choices=[('PROGRAMA AOS', 'Programa aos'), ('PROGRAMA INSOMNIO', 'Programa Insomnio')], max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('motivo_egreso', models.TextField(blank=True, max_length=500, null=True)),
                ('mes_capita', models.IntegerField()),
                ('valor_capita', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
