# Generated by Django 6.0.1 on 2026-01-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
