# Generated by Django 4.2.27 on 2026-01-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Hospitalizado'), ('SUSPENDIDO', 'Ambulatorio'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('motivo', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='patients.patient')),
            ],
        ),
    ]
