# Generated by Django 4.2.27 on 2026-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fecha_egreso',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='motivo_egreso',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ocupacion',
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnostico_clinico',
            field=models.TextField(choices=[('G47.3', 'Apnea del Sueño')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medico_remitente',
            field=models.CharField(choices=[('DR. JUAN PÉREZ', 'Dr. Juan Pérez'), ('DRA. MARÍA GÓMEZ', 'Dra. María Gómez'), ('MEGA ECOPETROL', 'Mega Ecopetrol')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='valor_capita',
            field=models.DecimalField(decimal_places=2, default=284000, max_digits=10),
        ),
    ]
