# Generated by Django 4.2.27 on 2026-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_barrio_remove_patient_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
