# Generated by Django 4.2.27 on 2026-01-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_ingreso_created_at_alter_ingreso_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mes_capita',
        ),
    ]
