# Generated by Django 4.2.27 on 2026-02-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_ingreso_options_alter_ingreso_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='valor_capita',
            field=models.DecimalField(decimal_places=2, default=259783, max_digits=10),
        ),
    ]
