# Generated by Django 4.2.27 on 2026-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_valor_capita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ciudad',
            field=models.CharField(choices=[('BUCARAMANGA', 'Bucaramanga'), ('FLORIDABLANCA', 'Floridablanca'), ('GIRON', 'Girón'), ('PIEDECUESTA', 'Piedecuesta'), ('BARRANCABERMEJA', 'Barrancabermeja'), ('BOGOTA', 'Bogotá, D.C.'), ('MEDELLIN', 'Medellín'), ('CALI', 'Cali'), ('BARRANQUILLA', 'Barranquilla'), ('CARTAGENA', 'Cartagena'), ('CUCUTA', 'Cúcuta'), ('IBAGUE', 'Ibagué'), ('PEREIRA', 'Pereira'), ('MANIZALES', 'Manizales'), ('NEIVA', 'Neiva'), ('VILLAVICENCIO', 'Villavicencio'), ('PASTO', 'Pasto'), ('MONTERIA', 'Montería'), ('VALLEDUPAR', 'Valledupar'), ('SANTA MARTA', 'Santa Marta'), ('POPAYAN', 'Popayán'), ('TUNJA', 'Tunja'), ('QUIBDO', 'Quibdó'), ('RIOHACHA', 'Riohacha'), ('FLORENCIA', 'Florencia'), ('YOPAL', 'Yopal'), ('SINCELEJO', 'Sincelejo'), ('ARMENIA', 'Armenia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='departamento',
            field=models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLANTICO', 'Atlántico'), ('BOLIVAR', 'Bolívar'), ('BOYACA', 'Boyacá'), ('CALDAS', 'Caldas'), ('CAQUETA', 'Caquetá'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCO', 'Chocó'), ('CORDOBA', 'Córdoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINIA', 'Guainía'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('LA_GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARINO', 'Nariño'), ('NORTE_SANTANDER', 'Norte de Santander'), ('PUTUMAYO', 'Putumayo'), ('QUINDIO', 'Quindío'), ('RISARALDA', 'Risaralda'), ('SAN_ANDRES', 'San Andrés y Providencia'), ('SANTANDER', 'Santander'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE_CAUCA', 'Valle del Cauca'), ('VAUPES', 'Vaupés'), ('VICHADA', 'Vichada')], default='SANTANDER', max_length=100),
        ),
    ]
