# Generated by Django 4.2.27 on 2026-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_ciudad_alter_patient_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ciudad',
            field=models.CharField(choices=[('BUCARAMANGA', 'Bucaramanga'), ('FLORIDABLANCA', 'Floridablanca'), ('GIRON', 'Girón'), ('PIEDECUESTA', 'Piedecuesta'), ('BARRANCABERMEJA', 'Barrancabermeja'), ('BOGOTA', 'Bogotá, D.C.'), ('MEDELLIN', 'Medellín'), ('CALI', 'Cali'), ('BARRANQUILLA', 'Barranquilla'), ('CARTAGENA', 'Cartagena'), ('CUCUTA', 'Cúcuta'), ('IBAGUE', 'Ibagué'), ('PEREIRA', 'Pereira'), ('MANIZALES', 'Manizales'), ('NEIVA', 'Neiva'), ('VILLAVICENCIO', 'Villavicencio'), ('PASTO', 'Pasto'), ('MONTERIA', 'Montería'), ('VALLEDUPAR', 'Valledupar'), ('SANTA MARTA', 'Santa Marta'), ('POPAYAN', 'Popayán'), ('TUNJA', 'Tunja'), ('QUIBDO', 'Quibdó'), ('RIOHACHA', 'Riohacha'), ('FLORENCIA', 'Florencia'), ('YOPAL', 'Yopal'), ('SINCELEJO', 'Sincelejo'), ('ARMENIA', 'Armenia'), ('SAN MARTIN', 'San Martín')], max_length=100),
        ),
    ]
