# Generated by Django 4.2.27 on 2026-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patient_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ciudad',
            field=models.CharField(choices=[('BUCARAMANGA', 'Bucaramanga'), ('FLORIDABLANCA', 'Floridablanca'), ('GIRON', 'Girón'), ('PIEDECUESTA', 'Piedecuesta'), ('BARRANCABERMEJA', 'Barrancabermeja'), ('LOS_SANTOS', 'Los Santos'), ('PUENTE_NACIONAL', 'Puente Nacional'), ('ZAPATOCA', 'Zapatoca'), ('SAN_GIL', 'San Gil'), ('CURITI', 'Curití'), ('PLAYON', 'Playón'), ('PUERTO_WILCHES', 'Puerto Wilches'), ('MALAGA', 'Málaga'), ('SABANA_DE_TORRES', 'Sabana de Torres'), ('SOCORRO', 'Socorro'), ('BOGOTA', 'Bogotá, D.C.'), ('MEDELLIN', 'Medellín'), ('CALI', 'Cali'), ('BARRANQUILLA', 'Barranquilla'), ('CARTAGENA', 'Cartagena'), ('CUCUTA', 'Cúcuta'), ('IBAGUE', 'Ibagué'), ('PEREIRA', 'Pereira'), ('MANIZALES', 'Manizales'), ('NEIVA', 'Neiva'), ('VILLAVICENCIO', 'Villavicencio'), ('PASTO', 'Pasto'), ('MONTERIA', 'Montería'), ('VALLEDUPAR', 'Valledupar'), ('SANTA MARTA', 'Santa Marta'), ('POPAYAN', 'Popayán'), ('TUNJA', 'Tunja'), ('QUIBDO', 'Quibdó'), ('RIOHACHA', 'Riohacha'), ('FLORENCIA', 'Florencia'), ('YOPAL', 'Yopal'), ('SINCELEJO', 'Sincelejo'), ('ARMENIA', 'Armenia'), ('SAN MARTIN', 'San Martín'), ('YONDO', 'Yondó')], max_length=100),
        ),
    ]
