# Generated by Django 6.0.1 on 2026-01-16 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_fecha_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_diario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_uso_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hipopnea_basal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hipopnea_residual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presion_ipap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presion_epap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('modo_ventilatorio', models.CharField(choices=[('CPAP', 'CPAP'), ('BPAP', 'BPAP'), ('BPAP ST', 'BPAP ST'), ('AUTOCPAP', 'AUTOCPAP'), ('AUTOBPAP', 'AUTOBPAP')], max_length=20)),
                ('mascara_cpap', models.CharField(choices=[('PILLOW NASAL', 'Pillow nasal'), ('NASAL', 'Nasal'), ('ORONASAL', 'Oronasal')], max_length=20)),
                ('tamaño_mascara', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=20)),
                ('etco2_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='patients.patient')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoreos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
