# Generated by Django 6.0.1 on 2026-01-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoreo',
            old_name='tamaño_mascara',
            new_name='tamano_mascara',
        ),
    ]
