# Generated by Django 6.0.1 on 2026-01-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_tamaño_mascara_monitoreo_tamano_mascara'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoreo',
            old_name='usu_diario',
            new_name='uso_diario',
        ),
    ]
