# Generated by Django 6.0.1 on 2026-01-19 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_usu_diario_monitoreo_uso_diario'),
        ('patients', '0002_alter_patient_fecha_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_depre_beck', models.IntegerField()),
                ('inventario_ansiedad_beck', models.IntegerField()),
                ('escala_atenas', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutriciones', to='patients.patient')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutriciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
