# Generated by Django 6.0.1 on 2026-01-19 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_psicologia'),
        ('patients', '0002_alter_patient_fecha_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologia',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psicologias', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='psicologia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psicologias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_nutricional', models.CharField(choices=[('DESNUTRICIÓN', 'Desnutrición'), ('EUTRÓFICO', 'Eutrófico'), ('SOBREPESO', 'Sobrepeso'), ('OBESIDAD I', 'Obesidad I'), ('OBESIDAD II', 'Obesidad II'), ('OBESIDAD III', 'Obesidad III')], max_length=20)),
                ('carbohidratos_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rumiacion', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=5)),
                ('cafeina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutriciones', to='patients.patient')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutriciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
