# Generated by Django 4.2.27 on 2026-01-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_psicologia_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutricion',
            options={'verbose_name': 'Nutrición', 'verbose_name_plural': 'Nutriciones'},
        ),
    ]
