# Generated by Django 4.2.27 on 2026-01-21 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_fecha_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0006_alter_nutricion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolisomnografiaTitulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_titulacion', models.DateField()),
                ('presion_ipap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presion_epap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ahi_residual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polisomnografias_titulaciones', to='patients.patient')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polisomnografias_titulaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolisomnografiaBasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_basal', models.DateField()),
                ('iah', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severidad_apnea', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('NORAMAL', 'Normal'), ('SEVERA', 'Severa')], max_length=50)),
                ('ido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polisomnografias_basales', to='patients.patient')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polisomnografias_basales_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Neumologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('medico_tratante', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neumologias', to='patients.patient')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neumologias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
