# Generated by Django 4.2.27 on 2026-01-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_polisomnografiatitulacion_polisomnografiabasal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polisomnografiatitulacion',
            name='tipo_titulacion',
            field=models.CharField(blank=True, choices=[('CPAP', 'CPAP'), ('BPAP', 'BPAP')], max_length=20, null=True, verbose_name='Tipo de Titulación'),
        ),
    ]
