# Generated by Django 4.2.27 on 2026-01-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_polisomnografiatitulacion_tipo_titulacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polisomnografiatitulacion',
            name='ahi_residual',
        ),
    ]
