# Generated by Django 4.2.27 on 2026-01-21 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_fecha_ingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0009_remove_polisomnografiatitulacion_ahi_residual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla_mascara', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=20)),
                ('marca_equipo', models.CharField(choices=[('BMC', 'BMC'), ('RESMED', 'ResMed'), ('PHILIPS RESPIRONICS', 'Philips RespiroNics'), ('SEFAN', 'Sefan'), ('DAM', 'Dam'), ('RESVENT', 'Resvent'), ('CURATIVE', 'Curative'), ('PRISMA', 'Prisma'), ('DEVILBIS', 'Devilbis')], max_length=100)),
                ('serial_equipo', models.CharField(max_length=100)),
                ('modo_ventiñlatorio', models.CharField(choices=[('CPAP', 'CPAP'), ('BiPAP', 'BiPAP'), ('BiPAP ST', 'BiPAP ST'), ('AUTOCPAP', 'AUTOCPAP'), ('AUTOBPAP', 'AUTOBPAP')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_medicos', to='patients.patient')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_medicos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
