# Generated by Django 4.2.27 on 2026-01-21 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_equipomedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomedico',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
