# Generated by Django 4.2.27 on 2026-01-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_equipomedico_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipomedico',
            old_name='modo_ventiñlatorio',
            new_name='modo_ventilatorio',
        ),
    ]
