# Generated by Django 4.2.27 on 2026-01-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_seguimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ['-fecha_atencion'], 'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
    ]
