# Generated by Django 4.2.27 on 2026-01-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_alter_seguimiento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polisomnografiabasal',
            options={'verbose_name': 'Polisomnografía Basal', 'verbose_name_plural': 'Polisomnografías Basales'},
        ),
        migrations.AlterModelOptions(
            name='polisomnografiatitulacion',
            options={'verbose_name': 'Polisomnografía de Titulación', 'verbose_name_plural': 'Polisomnografías de Titulación'},
        ),
    ]
