# Generated by Django 4.2.27 on 2026-01-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_ingreso'),
        ('exams', '0015_alter_polisomnografiabasal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipomedico',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='neumologia',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='nutricion',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='polisomnografiabasal',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='polisomnografiatitulacion',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='psicologia',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='patient',
        ),
        migrations.AddField(
            model_name='equipomedico',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_medicos', to='patients.ingreso'),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='patients.ingreso'),
        ),
        migrations.AddField(
            model_name='neumologia',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neumologias', to='patients.ingreso'),
        ),
        migrations.AddField(
            model_name='nutricion',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutriciones', to='patients.ingreso'),
        ),
        migrations.AddField(
            model_name='polisomnografiabasal',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polisomnografias_basales', to='patients.ingreso'),
        ),
        migrations.AddField(
            model_name='polisomnografiatitulacion',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polisomnografias_titulaciones', to='patients.ingreso'),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psicologias', to='patients.ingreso'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='patients.ingreso'),
        ),
    ]
