# Generated by Django 4.2.27 on 2026-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_remove_equipomedico_patient_remove_monitoreo_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polisomnografiabasal',
            name='eficiencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
