# Generated by Django 4.2.27 on 2026-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_polisomnografiabasal_eficiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='polisomnografiatitulacion',
            name='talla_mascara',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='No especificado', max_length=20),
        ),
        migrations.AddField(
            model_name='polisomnografiatitulacion',
            name='tipo_mascara',
            field=models.CharField(choices=[('PILLOW NASAL', 'Pillow nasal'), ('NASAL', 'Nasal'), ('ORONASAL', 'Oronasal')], default='No especificado', max_length=20),
        ),
    ]
