# Generated by Django 4.2.27 on 2026-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_polisomnografiatitulacion_talla_mascara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomedico',
            name='tipo_mascara_eq_medico',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
