# Generated by Django 4.2.27 on 2026-02-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_equipomedico_tipo_mascara_eq_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomedico',
            name='modo_ventilatorio',
            field=models.CharField(choices=[('CPAP', 'CPAP'), ('BiPAP', 'BiPAP'), ('BiPAP ST', 'BiPAP ST')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='modo_ventilatorio',
            field=models.CharField(choices=[('CPAP', 'CPAP'), ('BPAP', 'BPAP'), ('BPAP ST', 'BPAP ST')], max_length=20),
        ),
    ]
