# Generated by Django 4.2.27 on 2026-02-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_alter_equipomedico_modo_ventilatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polisomnografiabasal',
            name='severidad_apnea',
            field=models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('NORAMAL', 'Normal'), ('GRAVE', 'Grave')], max_length=50),
        ),
    ]
