# Generated by Django 4.2.27 on 2026-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_alter_polisomnografiabasal_severidad_apnea'),
    ]

    operations = [
        migrations.AddField(
            model_name='polisomnografiatitulacion',
            name='frecuencia_respiratoria',
            field=models.IntegerField(default=0, help_text='Respiraciones por minuto (rpm)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polisomnografiatitulacion',
            name='tipo_titulacion',
            field=models.CharField(blank=True, choices=[('CPAP', 'CPAP'), ('BPAP', 'BPAP'), ('BPAP ST', 'BPAP ST')], max_length=20, null=True, verbose_name='Tipo de Titulación'),
        ),
    ]
