# Generated by Django 4.2.27 on 2026-02-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_polisomnografiatitulacion_frecuencia_respiratoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomedico',
            name='referencia_mascara',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipomedico',
            name='tipo_mascara_eq_medico',
            field=models.CharField(choices=[('PILLOW NASAL', 'Pillow nasal'), ('NASAL', 'Nasal'), ('ORONASAL', 'Oronasal')], max_length=100),
        ),
    ]
