# Generated by Django 4.2.27 on 2026-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_equipomedico_referencia_mascara_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoreo',
            old_name='dias_uso_horas',
            new_name='dias_uso_horas_4',
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='horas_uso_diario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neumologia',
            name='especialidad',
            field=models.CharField(default='Sin especialidad', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipomedico',
            name='marca_equipo',
            field=models.CharField(choices=[('BMC', 'BMC'), ('RESMED', 'ResMed'), ('PHILIPS RESPIRONICS', 'Philips RespiroNics'), ('SEFAN', 'Sefan'), ('RESVENT', 'Resvent'), ('CURATIVE', 'Curative'), ('PRISMA', 'Prisma'), ('DEVILBIS', 'Devilbis')], max_length=100),
        ),
    ]
