# Generated by Django 4.2.27 on 2026-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_rename_dias_uso_horas_monitoreo_dias_uso_horas_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='frecuencia_respiratoria',
            field=models.IntegerField(default=0.0, help_text='Respiraciones por minuto (rpm)'),
            preserve_default=False,
        ),
    ]
