# Generated by Django 4.2.27 on 2026-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_monitoreo_frecuencia_respiratoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='etco2_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
