# Generated by Django 4.2.27 on 2026-02-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_alter_monitoreo_etco2_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='presion_epap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='presion_ipap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
