# Generated by Django 4.2.27 on 2026-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_alter_monitoreo_presion_epap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, help_text='Respiraciones por minuto (rpm)', null=True),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='presion_ipap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
