# Generated by Django 4.2.27 on 2026-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_alter_monitoreo_frecuencia_respiratoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='porcentaje_correccion',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado automáticamente: ((Basal - Residual) / Basal) * 100', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='hipopnea_basal',
            field=models.DecimalField(decimal_places=2, help_text='Copiado de la PSG Basal al momento del registro', max_digits=5),
        ),
    ]
