# Generated by Django 4.2.27 on 2026-02-13 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0008_alter_patient_valor_capita'),
        ('exams', '0029_monitoreo_porcentaje_correccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAdaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(verbose_name='Observaciones de Seguimiento')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_adaptaciones', to='patients.ingreso')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_adaptaciones_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Adaptación',
                'ordering': ['-created_at'],
            },
        ),
    ]
