# Generated by Django 4.2.27 on 2026-02-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_seguimientoadaptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polisomnografiatitulacion',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, help_text='Respiraciones por minuto (rpm)', null=True),
        ),
        migrations.AlterField(
            model_name='polisomnografiatitulacion',
            name='presion_epap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
