# Generated by Django 4.2.27 on 2026-03-24 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0031_alter_polisomnografiatitulacion_frecuencia_respiratoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologia',
            name='escala_atenas',
        ),
        migrations.AddField(
            model_name='psicologia',
            name='calidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologia',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologia',
            name='total',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
