# Generated by Django 4.2.27 on 2026-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_remove_psicologia_escala_atenas_psicologia_calidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologia',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
